/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jtqiu' at '4/29/16 8:39 AM' with Gradle 2.9
 *
 * @author jtqiu, @date 4/29/16 8:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
